version: '3.3'

services:
  server:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: play-tino-fe
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - 5173:5173